-- MySQL Script generated by MySQL Workbench
-- Sun Oct 30 17:39:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema slh-repository
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema slh-repository
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `slh-repository` DEFAULT CHARACTER SET utf8 ;
USE `slh-repository` ;

-- -----------------------------------------------------
-- Table `slh-repository`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slh-repository`.`User` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `accessLevel` INT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slh-repository`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slh-repository`.`Post` (
  `idPost` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `locked` TINYINT NULL,
  `dateCreated` DATETIME NULL,
  `lastEdited` DATETIME NULL,
  `mediaType` VARCHAR(4) NULL,
  `tags` JSON NULL,
  `description` LONGTEXT NULL
  PRIMARY KEY (`idPost`),
  INDEX `fk_Post_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `slh-repository`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
